### ISSUE TITLE
cannot change current working directory to the original directory: Permission denied

### ISSUE THREAD

**Issue by ghost** [smoser/pdftk#4] opened 2018-09-18 11:21 UTC
```
xxx@mimas:~$ sudo snap install pdftk
pdftk 2.02-4 from Scott Moser (smoser) installed
xxx@mimas:~$ pdftk 
cannot change current working directory to the original directory: Permission denied
```
Under Ubuntu 18.04.1 LTS  it does not work in a mounted (encfs encrypted) filesystem; works under my local home :(

PS.: Just unmounted the file system and remounted and now it works ...

**Comment by smoser** [comment] 2018-10-11 15:23
Duplicate of #1

**Comment by smoser** [comment] 2018-11-26 21:46
Please feel free to re-open if you think my diagnosis is wrong.

**Closed as completed by smoser** 2018-11-26 21:46 UTC
